// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1dCvo2KvPiG-Pg5AlyoOBbfUl0R_0kw',
    appId: '1:479630668260:web:b28765f3c2ede542f157f1',
    messagingSenderId: '479630668260',
    projectId: 'tri-go-app',
    authDomain: 'tri-go-app.firebaseapp.com',
    databaseURL: 'https://tri-go-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tri-go-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIj3N__iP20HpdS4fU7eL1dgDw8iRmDYg',
    appId: '1:479630668260:android:9bb04b42f8d83868f157f1',
    messagingSenderId: '479630668260',
    projectId: 'tri-go-app',
    databaseURL: 'https://tri-go-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tri-go-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGZQXLOixJatImYnmyPFnc-imLnWkIrfI',
    appId: '1:479630668260:ios:945c8d3fd71d90d6f157f1',
    messagingSenderId: '479630668260',
    projectId: 'tri-go-app',
    databaseURL: 'https://tri-go-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tri-go-app.firebasestorage.app',
    iosClientId: '479630668260-tv4ik2s7jq1457aiar234go0ro0g56l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.triGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGZQXLOixJatImYnmyPFnc-imLnWkIrfI',
    appId: '1:479630668260:ios:945c8d3fd71d90d6f157f1',
    messagingSenderId: '479630668260',
    projectId: 'tri-go-app',
    databaseURL: 'https://tri-go-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tri-go-app.firebasestorage.app',
    iosClientId: '479630668260-tv4ik2s7jq1457aiar234go0ro0g56l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.triGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ1dCvo2KvPiG-Pg5AlyoOBbfUl0R_0kw',
    appId: '1:479630668260:web:fbe3ac65b22d620bf157f1',
    messagingSenderId: '479630668260',
    projectId: 'tri-go-app',
    authDomain: 'tri-go-app.firebaseapp.com',
    databaseURL: 'https://tri-go-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tri-go-app.firebasestorage.app',
  );

}